#!/usr/bin/env python3
"""
Created by OpenCode.
Initialized: 2026-05-20
Updated: 2026-05-20

Point Cloud Generator CLI.

Converts an RGB image and its depth map into a colored 3D point cloud
(saved as an ASCII .ply file). Uses the pinhole camera model to back-project
every pixel into 3D space.

By default, the script re-inverts the depth map (since depth_map.py inverts
for ControlNet compatibility: black = near, white = far). After re-inversion,
near objects map to smaller Z values and far objects to larger Z values,
which is the standard expectation in 3D viewers. Use --no-invert-depth to
skip re-inversion and treat the depth map as-is.

Camera intrinsics are loaded automatically from an EXIF JSON file
(<stem>-exif.json, generated by exif_extractor.py). If unavailable, generic
fallback intrinsics are used (50 mm equivalent focal length on a 36 mm sensor).

Usage:
    python point_cloud.py photo.png [output.ply] [options]

Examples:
    # Auto-look for depth map and intrinsics, output photo-pointcloud.ply
    python point_cloud.py photo.png

    # Explicit depth map and intrinsics
    python point_cloud.py photo.png --depth photo-depthmap.png --exif photo-exif.json

    # Full resolution (larger file, more detail)
    python point_cloud.py photo.png --resolution full

    # Interactive configuration
    python point_cloud.py photo.png -i
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import subprocess
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# 1. Light-weight setup (no heavy imports yet)
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("point_cloud")

SUPPORTED_EXTENSIONS: set[str] = {
    ".png",
    ".jpg",
    ".jpeg",
    ".bmp",
    ".tiff",
    ".tif",
    ".webp",
}

REQUIRED_PACKAGES: dict[str, str] = {
    "cv2": "opencv-python",
    "numpy": "numpy",
    "PIL": "Pillow",
}

# ---------------------------------------------------------------------------
# 2. CLI argument parsing (--help works before any heavy setup)
# ---------------------------------------------------------------------------


def _build_parser() -> argparse.ArgumentParser:
    """Build and return the argument parser with full help text."""
    parser = argparse.ArgumentParser(
        prog="point_cloud.py",
        description="Generate a colored 3D point cloud (.ply) from an image and depth map.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Interactive mode (-i) lets you configure settings step-by-step in the terminal.

Depth & intrinsics resolution:
  • Not specified          -> auto-look for <stem>-depthmap.png and <stem>-exif.json
  • --depth <path>         -> use the provided depth map image
  • --exif <path>          -> use the provided EXIF JSON for camera intrinsics
  • Auto-lookup missing    -> prompt to run the respective script to generate one

Output rules:
  • Single file + no output  ->  <name>-pointcloud.ply in same folder
  • Single file + output     ->  written to specified path

Examples:
  %(prog)s photo.png
  %(prog)s photo.png --depth depth.png --exif meta.json
  %(prog)s photo.png --resolution full
  %(prog)s photo.png -i
        """,
    )

    parser.add_argument(
        "input",
        help="Input RGB image file",
    )
    parser.add_argument(
        "output",
        nargs="?",
        help="Output .ply file (optional)",
    )
    parser.add_argument(
        "-i",
        "--interactive",
        action="store_true",
        help="Enter interactive mode to configure settings step-by-step",
    )

    # Core settings
    parser.add_argument(
        "--depth",
        dest="depth_input",
        metavar="PATH",
        help="Explicit path to a depth map image (overrides auto-lookup)",
    )
    parser.add_argument(
        "--exif",
        dest="exif_input",
        metavar="PATH",
        help="Explicit path to an EXIF JSON file (overrides auto-lookup)",
    )
    parser.add_argument(
        "--resolution",
        choices=["full", "half", "quarter"],
        default="half",
        help="Point cloud resolution relative to the input image. "
             "full = original size, half = 1/2 width & height, quarter = 1/4. "
             "(default: half)",
    )
    parser.add_argument(
        "--no-invert-depth",
        action="store_true",
        help="Do NOT re-invert depth values. By default, depth is re-inverted "
             "so that near objects have smaller Z values.",
    )
    parser.add_argument(
        "--format",
        choices=["ply"],
        default="ply",
        help="Output format (default: ply)",
    )

    return parser


# ---------------------------------------------------------------------------
# 3. Virtual Environment & Dependency Management
# ---------------------------------------------------------------------------


def _ask_user(question: str, default: bool = True) -> bool:
    """Prompt the user for a yes/no answer in the terminal."""
    hint = "Y/n" if default else "y/N"
    while True:
        try:
            response = input(f"{question} [{hint}]: ").strip().lower()
        except EOFError:
            logger.info("Non-interactive environment detected. Using default: %s", default)
            return default
        if not response:
            return default
        if response in ("y", "yes"):
            return True
        if response in ("n", "no"):
            return False
        print("  Please answer 'y' or 'n'.")


def _in_virtual_env() -> bool:
    """Return True if the current interpreter is running inside a venv."""
    return (
        hasattr(sys, "real_prefix")
        or (getattr(sys, "base_prefix", None) != sys.prefix)
        or os.environ.get("VIRTUAL_ENV") is not None
    )


def _get_venv_python(venv_dir: Path) -> Path:
    """Return the python executable inside the given venv."""
    if os.name == "nt":
        return venv_dir / "Scripts" / "python.exe"
    return venv_dir / "bin" / "python"


def _ensure_venv() -> None:
    """
    Ensure the script runs inside a virtual environment.

    If the current interpreter is already inside a venv, do nothing.
    If a .venv directory already exists next to the script, restart into it
    automatically (no prompt needed).
    Otherwise, ask the user to create a new venv and restart into it.
    """
    if _in_virtual_env():
        logger.debug("Already running inside a virtual environment.")
        return

    venv_path = Path(__file__).resolve().parent / ".venv"

    if venv_path.exists() and venv_path.is_dir():
        logger.info("Found existing virtual environment: %s", venv_path)
        venv_python = _get_venv_python(venv_path)
        if venv_python.exists():
            logger.info("Restarting script inside the virtual environment...")
            script_path = Path(__file__).resolve()
            os.execv(
                str(venv_python),
                [str(venv_python), str(script_path)] + sys.argv[1:],
            )
        else:
            logger.warning(
                "Virtual environment exists but python executable not found: %s",
                venv_python,
            )

    logger.warning("You are NOT running inside a virtual environment.")
    logger.info("It is strongly recommended to use a venv to avoid dependency conflicts.")

    if not _ask_user("Create a virtual environment?", default=True):
        logger.info("Exiting. Please activate a virtual environment and run again.")
        sys.exit(0)

    logger.info("Creating virtual environment at: %s", venv_path)

    try:
        subprocess.check_call([sys.executable, "-m", "venv", str(venv_path)])
    except subprocess.CalledProcessError as exc:
        logger.error("Failed to create virtual environment: %s", exc)
        sys.exit(1)

    venv_python = _get_venv_python(venv_path)
    if not venv_python.exists():
        logger.error(
            "Virtual environment created but python executable not found: %s",
            venv_python,
        )
        sys.exit(1)

    logger.info("Restarting script inside the virtual environment...")
    script_path = Path(__file__).resolve()
    os.execv(str(venv_python), [str(venv_python), str(script_path)] + sys.argv[1:])


def _check_dependencies() -> list[str]:
    """Check for missing packages and return their pip install names."""
    missing: list[str] = []
    for module, pip_name in REQUIRED_PACKAGES.items():
        try:
            __import__(module)
        except ImportError:
            missing.append(pip_name)
    return missing


def _install_dependencies(packages: list[str]) -> None:
    """Install missing packages using pip in the current environment."""
    logger.info("Installing: %s", ", ".join(packages))
    cmd = [sys.executable, "-m", "pip", "install"] + packages
    try:
        subprocess.check_call(cmd)
        logger.info("Dependencies installed successfully.")
    except subprocess.CalledProcessError as exc:
        logger.error("Failed to install dependencies: %s", exc)
        sys.exit(1)


def _ensure_dependencies() -> None:
    """Ensure required packages are installed."""
    missing = _check_dependencies()
    if not missing:
        return

    logger.warning("Missing required packages: %s", ", ".join(missing))
    logger.info("These packages are needed to generate point clouds.")
    if not _ask_user("Install missing dependencies now?", default=True):
        logger.info(
            "Exiting. Install manually with: pip install %s",
            " ".join(missing),
        )
        sys.exit(0)
    _install_dependencies(missing)


def ensure_environment() -> None:
    """Top-level environment gate: venv first, then dependencies."""
    _ensure_venv()
    _ensure_dependencies()


# ---------------------------------------------------------------------------
# 4. Heavy imports (only after environment is confirmed)
# ---------------------------------------------------------------------------

if "--help" in sys.argv or "-h" in sys.argv:
    _build_parser().print_help()
    sys.exit(0)

ensure_environment()

import cv2  # noqa: E402
import numpy as np  # noqa: E402


# ---------------------------------------------------------------------------
# 5. Core point-cloud logic
# ---------------------------------------------------------------------------


def _find_script(name: str) -> Path | None:
    """Return the path to a sibling script in the same directory."""
    script_dir = Path(__file__).resolve().parent
    candidate = script_dir / name
    if candidate.exists():
        return candidate
    logger.warning("%s not found in script directory: %s", name, script_dir)
    return None


def _run_depth_map(rgb_path: Path) -> Path | None:
    """
    Run depth_map.py to generate a depth map for the given image.

    Args:
        rgb_path: Path to the RGB image.

    Returns:
        Path to the generated depth map, or None if generation failed.
    """
    depth_script = _find_script("depth_map.py")
    if depth_script is None:
        return None

    logger.info("Running depth_map.py to generate depth map...")
    result = subprocess.run(
        [sys.executable, str(depth_script), str(rgb_path)],
        cwd=str(depth_script.parent),
    )

    if result.returncode != 0:
        logger.error("depth_map.py failed with exit code %d", result.returncode)
        return None

    expected = rgb_path.parent / f"{rgb_path.stem}-depthmap.png"
    if expected.exists():
        logger.info("Generated depth map: %s", expected)
        return expected

    candidates = list(rgb_path.parent.glob(f"{rgb_path.stem}-depthmap.*"))
    if candidates:
        logger.info("Generated depth map: %s", candidates[0])
        return candidates[0]

    logger.error("depth_map.py completed but no output file was found.")
    return None


def _run_exif_extractor(rgb_path: Path) -> Path | None:
    """
    Run exif_extractor.py to generate EXIF JSON for the given image.

    Args:
        rgb_path: Path to the RGB image.

    Returns:
        Path to the generated EXIF JSON, or None if generation failed.
    """
    exif_script = _find_script("exif_extractor.py")
    if exif_script is None:
        return None

    logger.info("Running exif_extractor.py to generate EXIF metadata...")
    result = subprocess.run(
        [sys.executable, str(exif_script), str(rgb_path)],
        cwd=str(exif_script.parent),
    )

    if result.returncode != 0:
        logger.error("exif_extractor.py failed with exit code %d", result.returncode)
        return None

    expected = rgb_path.parent / f"{rgb_path.stem}-exif.json"
    if expected.exists():
        logger.info("Generated EXIF JSON: %s", expected)
        return expected

    candidates = list(rgb_path.parent.glob(f"{rgb_path.stem}-exif.*"))
    if candidates:
        logger.info("Generated EXIF JSON: %s", candidates[0])
        return candidates[0]

    logger.error("exif_extractor.py completed but no output file was found.")
    return None


def find_depth_map(rgb_path: Path, depth_arg: str | None) -> Path | None:
    """
    Resolve the depth map path.

    Resolution order:
      1. If --depth is provided, use it directly.
      2. Auto-look for <stem>-depthmap.png next to the RGB image.
      3. If not found, ask to run depth_map.py, then check again.

    Args:
        rgb_path: Path to the input RGB image.
        depth_arg: Optional explicit depth map path from --depth.

    Returns:
        Resolved Path to the depth map, or None if unavailable.
    """
    if depth_arg:
        depth_path = Path(depth_arg).resolve()
        if not depth_path.exists():
            logger.error("Specified depth map not found: %s", depth_path)
            return None
        logger.info("Using explicit depth map: %s", depth_path)
        return depth_path

    expected = rgb_path.parent / f"{rgb_path.stem}-depthmap.png"
    if expected.exists():
        logger.info("Found depth map: %s", expected)
        return expected

    logger.warning("Depth map not found: %s", expected)
    if _ask_user("Run depth_map.py to generate the depth map?", default=True):
        generated = _run_depth_map(rgb_path)
        if generated is not None and generated.exists():
            return generated

    logger.error(
        "No depth map available. Provide one with --depth or generate it first."
    )
    return None


def find_exif_json(rgb_path: Path, exif_arg: str | None) -> Path | None:
    """
    Resolve the EXIF JSON path.

    Resolution order:
      1. If --exif is provided, use it directly.
      2. Auto-look for <stem>-exif.json next to the RGB image.
      3. If not found, ask to run exif_extractor.py, then check again.

    Args:
        rgb_path: Path to the input RGB image.
        exif_arg: Optional explicit EXIF JSON path from --exif.

    Returns:
        Resolved Path to the EXIF JSON, or None if unavailable.
    """
    if exif_arg:
        exif_path = Path(exif_arg).resolve()
        if not exif_path.exists():
            logger.error("Specified EXIF JSON not found: %s", exif_path)
            return None
        logger.info("Using explicit EXIF JSON: %s", exif_path)
        return exif_path

    expected = rgb_path.parent / f"{rgb_path.stem}-exif.json"
    if expected.exists():
        logger.info("Found EXIF JSON: %s", expected)
        return expected

    logger.warning("EXIF JSON not found: %s", expected)
    if _ask_user("Run exif_extractor.py to generate EXIF metadata?", default=True):
        generated = _run_exif_extractor(rgb_path)
        if generated is not None and generated.exists():
            return generated

    logger.warning(
        "No EXIF metadata available. Will use generic fallback intrinsics."
    )
    return None


def load_intrinsics(
    exif_path: Path | None, width: int, height: int
) -> tuple[float, float, float, float]:
    """
    Load or compute camera intrinsics (fx, fy, cx, cy).

    Args:
        exif_path: Path to EXIF JSON, or None for fallback.
        width: Image width in pixels.
        height: Image height in pixels.

    Returns:
        (fx, fy, cx, cy) as floats.
    """
    cx = width / 2.0
    cy = height / 2.0

    if exif_path is not None and exif_path.exists():
        try:
            with open(exif_path, "r", encoding="utf-8") as f:
                data = json.load(f)

            intrinsics = data.get("computed_intrinsics", {})
            focal_px = intrinsics.get("focal_length_px")

            if focal_px is not None:
                fx = float(focal_px)
                fy = fx  # assume square pixels
                logger.info(
                    "Loaded intrinsics from EXIF: fx=%.2f, fy=%.2f, cx=%.2f, cy=%.2f",
                    fx, fy, cx, cy,
                )
                return fx, fy, cx, cy

            # Try deriving from focal_length_mm + sensor width
            focal_mm = data.get("focal_length_mm")
            focal_35 = data.get("focal_length_35mm_equiv")

            if focal_mm is not None:
                # If sensor info not in computed_intrinsics, estimate from 35mm equiv
                if focal_35 is not None:
                    # sensor_width = focal_mm * 36 / focal_35
                    sensor_width = focal_mm * 36.0 / focal_35
                else:
                    sensor_width = 36.0  # fallback full-frame assumption

                fx = float(focal_mm) * width / sensor_width
                fy = fx  # square pixels
                logger.info(
                    "Derived intrinsics from focal length: fx=%.2f, fy=%.2f, "
                    "cx=%.2f, cy=%.2f (sensor_width=%.2f mm)",
                    fx, fy, cx, cy, sensor_width,
                )
                return fx, fy, cx, cy

        except Exception as exc:
            logger.warning("Failed to read EXIF JSON (%s). Using fallback intrinsics.", exc)

    # Generic fallback
    focal_mm = 50.0
    sensor_width_mm = 36.0
    fx = focal_mm * width / sensor_width_mm
    fy = fx
    logger.warning(
        "Using fallback intrinsics: fx=%.2f, fy=%.2f, cx=%.2f, cy=%.2f "
        "(50 mm equiv on 36 mm sensor). Point cloud scale will be approximate.",
        fx, fy, cx, cy,
    )
    return fx, fy, cx, cy


def load_image_bgr(path: Path) -> np.ndarray | None:
    """Load an image with OpenCV, preserving EXIF orientation."""
    from PIL import Image as PILImage
    from PIL import ImageOps

    try:
        pil_img = PILImage.open(str(path))
        pil_img = ImageOps.exif_transpose(pil_img)
        img_rgb = np.array(pil_img)

        if len(img_rgb.shape) == 3 and img_rgb.shape[2] >= 3:
            if img_rgb.shape[2] == 3:
                return cv2.cvtColor(img_rgb, cv2.COLOR_RGB2BGR)
            return cv2.cvtColor(img_rgb, cv2.COLOR_RGBA2BGRA)
        return img_rgb
    except Exception as exc:
        logger.error("Failed to load image: %s — %s", path, exc)
        return None


def create_point_cloud(
    rgb: np.ndarray,
    depth: np.ndarray,
    fx: float,
    fy: float,
    cx: float,
    cy: float,
    invert_depth: bool,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """
    Back-project an RGB image and depth map into 3D points.

    Args:
        rgb: BGR image, shape (H, W, 3).
        depth: Grayscale depth map, shape (H, W) or (H, W, 1).
        fx, fy: Focal lengths in pixels.
        cx, cy: Principal point.
        invert_depth: If True, re-invert depth so near -> small Z.

    Returns:
        Tuple of flat arrays (X, Y, Z, R, G, B).
    """
    h, w = rgb.shape[:2]

    # Ensure depth is single channel
    if len(depth.shape) == 3:
        depth_gray = cv2.cvtColor(depth, cv2.COLOR_BGR2GRAY)
    else:
        depth_gray = depth

    # Normalize depth to [0, 1]
    depth_norm = depth_gray.astype(np.float32) / 255.0

    # Re-invert depth by default (depth_map.py inverts for ControlNet:
    # black = near, white = far). Re-inverting restores:
    #   small Z value = near, large Z value = far.
    if invert_depth:
        depth_norm = 1.0 - depth_norm

    # Coordinate grids
    u = np.arange(w, dtype=np.float32)
    v = np.arange(h, dtype=np.float32)
    uu, vv = np.meshgrid(u, v)

    # Back-projection
    Z = depth_norm  # relative depth; scale is arbitrary for monocular depth
    X = (uu - cx) * Z / fx
    Y = (vv - cy) * Z / fy

    # Extract colors (BGR → RGB for PLY)
    b = rgb[:, :, 0].astype(np.uint8)
    g = rgb[:, :, 1].astype(np.uint8)
    r = rgb[:, :, 2].astype(np.uint8)

    return (
        X.ravel(),
        Y.ravel(),
        Z.ravel(),
        r.ravel(),
        g.ravel(),
        b.ravel(),
    )


def write_ply(
    path: Path,
    X: np.ndarray,
    Y: np.ndarray,
    Z: np.ndarray,
    R: np.ndarray,
    G: np.ndarray,
    B: np.ndarray,
) -> bool:
    """
    Write a point cloud to an ASCII .ply file.

    Args:
        path: Output file path.
        X, Y, Z: Float coordinate arrays.
        R, G, B: UInt8 color arrays.

    Returns:
        True on success.
    """
    n_points = X.shape[0]
    header = (
        "ply\n"
        "format ascii 1.0\n"
        f"element vertex {n_points}\n"
        "property float x\n"
        "property float y\n"
        "property float z\n"
        "property uchar red\n"
        "property uchar green\n"
        "property uchar blue\n"
        "end_header\n"
    )

    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        points = np.column_stack([X, Y, Z, R, G, B])
        with open(path, "w", encoding="ascii") as f:
            f.write(header)
            np.savetxt(f, points, fmt="%.6f %.6f %.6f %d %d %d")
        logger.info("Saved point cloud: %s (%d points)", path, n_points)
        return True
    except Exception as exc:
        logger.error("Failed to write .ply file: %s", exc)
        return False


def resolve_output_path(rgb_path: Path, output_arg: str | None) -> Path:
    """Determine the output .ply file path."""
    if output_arg:
        out = Path(output_arg)
        if output_arg.endswith(("/", "\\")) or (out.exists() and out.is_dir()):
            return out / f"{rgb_path.stem}-pointcloud.ply"
        if out.suffix.lower() != ".ply":
            return out.with_suffix(".ply")
        return out
    return rgb_path.parent / f"{rgb_path.stem}-pointcloud.ply"


# ---------------------------------------------------------------------------
# 6. Interactive mode
# ---------------------------------------------------------------------------


def interactive_configure(args: argparse.Namespace) -> argparse.Namespace:
    """
    Guide the user through configuration in the terminal.

    Overrides any command-line settings with the user's interactive choices.
    """
    print("\n" + "=" * 60)
    print("  Interactive Configuration Mode")
    print("=" * 60 + "\n")

    # --- Resolution ---
    resolutions = {
        "1": ("full", "original image resolution (largest file)"),
        "2": ("half", "half resolution (good balance, default)"),
        "3": ("quarter", "quarter resolution (smallest file)"),
    }
    print("Point cloud resolution:")
    for key, (name, desc) in resolutions.items():
        print(f"  {key}. {name} — {desc}")
    while True:
        choice = input("Enter choice [1-3, default: 2]: ").strip()
        if not choice:
            break
        if choice in resolutions:
            args.resolution = resolutions[choice][0]
            break
        print("  Invalid choice. Please enter 1, 2, or 3.")

    # --- Additional settings? ---
    if _ask_user("Do you want to specify additional settings?", default=False):
        # Depth map
        depth_input = input(
            "Depth map path (leave empty for auto-lookup): "
        ).strip()
        if depth_input:
            args.depth_input = depth_input

        # EXIF
        exif_input = input(
            "EXIF JSON path (leave empty for auto-lookup): "
        ).strip()
        if exif_input:
            args.exif_input = exif_input

        # Depth inversion
        args.no_invert_depth = not _ask_user(
            "Re-invert depth so near objects have smaller Z values?",
            default=True,
        )

    print("\n" + "=" * 60)
    print("  Configuration complete!")
    print("=" * 60 + "\n")
    return args


# ---------------------------------------------------------------------------
# 7. Main entry point
# ---------------------------------------------------------------------------


def main() -> int:
    """Parse arguments, optionally enter interactive mode, and generate point cloud."""
    parser = _build_parser()
    args = parser.parse_args()

    # Interactive configuration overrides CLI flags
    if args.interactive:
        args = interactive_configure(args)

    # Resolve and validate input
    rgb_path = Path(args.input).resolve()
    if not rgb_path.exists():
        logger.error("Input image not found: %s", rgb_path)
        return 1

    if not rgb_path.is_file():
        logger.error("Input must be a single image file: %s", rgb_path)
        return 1

    if rgb_path.suffix.lower() not in SUPPORTED_EXTENSIONS:
        logger.error("Unsupported input file format: %s", rgb_path.suffix)
        return 1

    # Find depth map
    depth_path = find_depth_map(rgb_path, args.depth_input)
    if depth_path is None:
        return 1

    # Find EXIF JSON (optional — falls back to generic intrinsics)
    exif_path = find_exif_json(rgb_path, args.exif_input)

    # Resolve output path
    output_path = resolve_output_path(rgb_path, args.output)

    # Load images
    rgb = load_image_bgr(rgb_path)
    depth = load_image_bgr(depth_path)
    if rgb is None or depth is None:
        return 1

    # Determine target resolution
    h_orig, w_orig = rgb.shape[:2]
    scale_map = {"full": 1.0, "half": 0.5, "quarter": 0.25}
    scale = scale_map[args.resolution]
    target_w = int(w_orig * scale)
    target_h = int(h_orig * scale)

    if scale < 1.0:
        logger.info(
            "Resizing to %s resolution: %dx%d → %dx%d",
            args.resolution, w_orig, h_orig, target_w, target_h,
        )
        rgb = cv2.resize(rgb, (target_w, target_h), interpolation=cv2.INTER_LINEAR)
        depth = cv2.resize(depth, (target_w, target_h), interpolation=cv2.INTER_LINEAR)
    else:
        logger.info("Using full resolution: %dx%d", w_orig, h_orig)

    # Load intrinsics
    fx, fy, cx, cy = load_intrinsics(exif_path, target_w, target_h)

    # Summary before processing
    logger.info("Input:    %s", rgb_path)
    logger.info("Depth:    %s", depth_path)
    logger.info("EXIF:     %s", exif_path if exif_path else "(fallback)")
    logger.info("Output:   %s", output_path)
    logger.info("Size:     %dx%d", target_w, target_h)
    logger.info("Invert:   %s", not args.no_invert_depth)
    logger.info("Intrinsics: fx=%.2f, fy=%.2f, cx=%.2f, cy=%.2f", fx, fy, cx, cy)

    # Generate point cloud
    try:
        X, Y, Z, R, G, B = create_point_cloud(
            rgb, depth, fx, fy, cx, cy, invert_depth=not args.no_invert_depth,
        )
    except Exception as exc:
        logger.error("Failed to create point cloud: %s", exc)
        return 1

    # Save
    if not write_ply(output_path, X, Y, Z, R, G, B):
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
